# ===============================
# SPRING CONFIGS
# ===============================

spring:
  main:
    allow-circular-references: true
  application:
    name: weekend_fun
  liquibase:
    enabled: true
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: none
        show_sql: false
    open-in-view: false
    hibernate:
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
        physical-strategy: org.hibernate.boot.model.naming.CamelCaseToUnderscoresNamingStrategy
  datasource:
    tomcat:
      test-while-idle: true
    url: jdbc:postgresql://localhost:5432/weekend_fun
    username: weekend_fun
    password: weekend_fun

# ===============================
# FILE CONFIGS
# ===============================
file:
  path: "/Users/Marlvin_1/Downloads/tos.product_texts.json"